// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHRKTS32kJq4jtNP-Talg8gwDChM1yAyA',
    appId: '1:1010526533335:web:c8e80f663e1bc604b46292',
    messagingSenderId: '1010526533335',
    projectId: 'vehicle-6941d',
    authDomain: 'vehicle-6941d.firebaseapp.com',
    storageBucket: 'vehicle-6941d.firebasestorage.app',
    measurementId: 'G-XT4EE0V6FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9d1tjJAGRRrCbJ8T57CinFQZcMK5f6yQ',
    appId: '1:1010526533335:android:ff55089c2ac8a57fb46292',
    messagingSenderId: '1010526533335',
    projectId: 'vehicle-6941d',
    storageBucket: 'vehicle-6941d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFUP7JuUCW8xASDynWaTUNXTBEPU47oQg',
    appId: '1:1010526533335:ios:d9577ea31899e692b46292',
    messagingSenderId: '1010526533335',
    projectId: 'vehicle-6941d',
    storageBucket: 'vehicle-6941d.firebasestorage.app',
    iosBundleId: 'com.example.vehicle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFUP7JuUCW8xASDynWaTUNXTBEPU47oQg',
    appId: '1:1010526533335:ios:d9577ea31899e692b46292',
    messagingSenderId: '1010526533335',
    projectId: 'vehicle-6941d',
    storageBucket: 'vehicle-6941d.firebasestorage.app',
    iosBundleId: 'com.example.vehicle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHRKTS32kJq4jtNP-Talg8gwDChM1yAyA',
    appId: '1:1010526533335:web:97e3865a36a0c9ebb46292',
    messagingSenderId: '1010526533335',
    projectId: 'vehicle-6941d',
    authDomain: 'vehicle-6941d.firebaseapp.com',
    storageBucket: 'vehicle-6941d.firebasestorage.app',
    measurementId: 'G-82T6N3E8T5',
  );
}
